// export const FLIGHTS_PER_MONTH_URL = "https://uaa.azurewebsites.net/api/flights-per-month"
// export const FLIGHTS_PER_MONTH_FROM_ORIGINS_URL = "https://uaa.azurewebsites.net/api/flights-per-month-from-dest"
// export const FLIGHTS_PER_MONTH_FROM_ORIGINS_PERCENTAGE_URL = "https://uaa.azurewebsites.net/api/flights-per-month-from-dest-percentage"
// export const FLIGHTS_PER_TOP10_DESTINATIONS_PER_ORIGINS_URL = "https://uaa.azurewebsites.net/api/top-10-dest-nr-of-flights-per-main-origins"
// export const FLIGHTS_TOP10_DESTINATIONS = "https://uaa.azurewebsites.net/api/top-10-dest-nr-of-flights";
export const FLIGHTS_CHART_DATA = "https://uaa.azurewebsites.net/api/chart-data"; 
export const TEMP_VALUES_ORIGINS = "https://uaa.azurewebsites.net/api/weather/values-for-main-origins";
export const WEATHER_OBSERVATION_COUNT_ORIGINS = "https://uaa.azurewebsites.net/api/weather/count-for-main-origins";
export const JFK_DAILY_MEAN_TEMP = "https://uaa.azurewebsites.net/api/weather/jfk-mean-temp-daily"; 
export const ORIGINS_DAILY_MEAN_TEMP = "https://uaa.azurewebsites.net/api/weather/mean-temp-daily-origin"